-- Sanity checks for KPI views
SELECT * FROM ATLAS_VW_KPI_TRADES_PER_DAY_7D;
SELECT * FROM ATLAS_VW_KPI_GROSS_NOTIONAL_MTD;
SELECT * FROM ATLAS_VW_KPI_TOP_ACCOUNTS_30D FETCH FIRST 5 ROWS ONLY;
SELECT * FROM ATLAS_VW_KPI_DQ_OPEN;
SELECT * FROM ATLAS_VW_KPI_TRADES_7D_MA;

-- Saved reports
SELECT * FROM ATLAS_VW_RPT_WEEKLY_SUMMARY;
SELECT * FROM ATLAS_VW_RPT_MONTHLY_SUMMARY;

-- Example “exportables” (copy results to CSV from LiveSQL UI):
-- 1) Top accounts 30d
SELECT * FROM ATLAS_VW_KPI_TOP_ACCOUNTS_30D ORDER BY notional_sum DESC;
-- 2) MTD notional by instrument
SELECT * FROM ATLAS_VW_KPI_GROSS_NOTIONAL_MTD ORDER BY gross_notional_mtd DESC;
