--------------------------------------------------------------------------------
-- ATLAS Investment Demo - Core Tables (structure only)
--------------------------------------------------------------------------------

-- Reference / Master data
CREATE TABLE ATLAS_INSTRUMENT (
  INSTRUMENT_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  SYMBOL           VARCHAR2(24)    NOT NULL,      -- e.g., AAPL, MSFT, BNDKWT
  INSTRUMENT_TYPE  VARCHAR2(20)    NOT NULL,      -- EQUITY, BOND, FUND, FX
  CURRENCY_CODE    VARCHAR2(3)     NOT NULL       -- KWD, USD, EUR
);

CREATE TABLE ATLAS_ACCOUNT (
  ACCOUNT_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ACCOUNT_NAME     VARCHAR2(60)    NOT NULL,      -- e.g., Pension Fund A
  REGION_CODE      VARCHAR2(8)     NOT NULL       -- KWT, GCC, EMEA, etc.
);

-- Transactional data
CREATE TABLE ATLAS_TRADE (
  TRADE_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TRADE_DT         DATE             NOT NULL,
  INSTRUMENT_ID    NUMBER           NOT NULL,
  ACCOUNT_ID       NUMBER           NOT NULL,
  SIDE             VARCHAR2(4)      NOT NULL,     -- BUY / SELL
  QTY              NUMBER(12,2)     NOT NULL,
  PRICE            NUMBER(12,4)     NOT NULL,
  ENTERED_BY       VARCHAR2(60)     NOT NULL,     -- username or email
  NOTE             VARCHAR2(200)
  -- FKs and checks will be added in 020_constraints.sql
);

-- Position snapshots (end-of-day / point-in-time)
CREATE TABLE ATLAS_POSITION (
  POSITION_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ASOF_DT          DATE             NOT NULL,
  INSTRUMENT_ID    NUMBER           NOT NULL,
  ACCOUNT_ID       NUMBER           NOT NULL,
  QTY              NUMBER(14,4)     NOT NULL
  -- Uniqueness/FKs in 020_constraints.sql
);

-- Simple audit trail
CREATE TABLE ATLAS_AUDIT (
  AUDIT_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TS               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  ACTOR            VARCHAR2(60) NOT NULL,         -- who
  ACTION           VARCHAR2(30) NOT NULL,         -- what (PLACE_TRADE, CANCEL, ...)
  ENTITY           VARCHAR2(30) NOT NULL,         -- ATLAS_TRADE, ATLAS_ACCOUNT, ...
  ENTITY_ID        NUMBER       NOT NULL,         -- PK value
  DETAILS          VARCHAR2(4000)                 -- free text / JSON snippet
);
