--------------------------------------------------------------------------------
-- ATLAS Investment Demo - Constraints (FKs, CHECKs, UNIQUEs, NOT NULL)
-- Run after 010_tables.sql
--------------------------------------------------------------------------------

-- INSTRUMENT: each SYMBOL should be unique; simple domain checks
ALTER TABLE ATLAS_INSTRUMENT
  ADD CONSTRAINT ATLAS_INSTRUMENT_UK1 UNIQUE (SYMBOL);

ALTER TABLE ATLAS_INSTRUMENT
  ADD CONSTRAINT ATLAS_INSTRUMENT_CHK1
  CHECK (INSTRUMENT_TYPE IN ('EQUITY','BOND','FUND','FX'));

ALTER TABLE ATLAS_INSTRUMENT
  ADD CONSTRAINT ATLAS_INSTRUMENT_CHK2
  CHECK (LENGTH(CURRENCY_CODE)=3);

-- ACCOUNT: region code length sanity check
ALTER TABLE ATLAS_ACCOUNT
  ADD CONSTRAINT ATLAS_ACCOUNT_CHK1
  CHECK (LENGTH(REGION_CODE) BETWEEN 2 AND 8);

-- TRADE: FKs to reference data
ALTER TABLE ATLAS_TRADE
  ADD CONSTRAINT ATLAS_TRADE_FK1 FOREIGN KEY (INSTRUMENT_ID)
  REFERENCES ATLAS_INSTRUMENT(INSTRUMENT_ID);

ALTER TABLE ATLAS_TRADE
  ADD CONSTRAINT ATLAS_TRADE_FK2 FOREIGN KEY (ACCOUNT_ID)
  REFERENCES ATLAS_ACCOUNT(ACCOUNT_ID);

-- TRADE: valid side/positive qty & price; basic date sanity
ALTER TABLE ATLAS_TRADE
  ADD CONSTRAINT ATLAS_TRADE_CHK1 CHECK (SIDE IN ('BUY','SELL'));

ALTER TABLE ATLAS_TRADE
  ADD CONSTRAINT ATLAS_TRADE_CHK2 CHECK (QTY  > 0);

ALTER TABLE ATLAS_TRADE
  ADD CONSTRAINT ATLAS_TRADE_CHK3 CHECK (PRICE > 0);

ALTER TABLE ATLAS_TRADE
  ADD CONSTRAINT ATLAS_TRADE_CHK4 CHECK (TRADE_DT >= DATE '2000-01-01'); -- demo

-- POSITION: FK relations and NATURAL uniqueness:
-- only one snapshot per (ASOF_DT, INSTRUMENT_ID, ACCOUNT_ID)
ALTER TABLE ATLAS_POSITION
  ADD CONSTRAINT ATLAS_POSITION_FK1 FOREIGN KEY (INSTRUMENT_ID)
  REFERENCES ATLAS_INSTRUMENT(INSTRUMENT_ID);

ALTER TABLE ATLAS_POSITION
  ADD CONSTRAINT ATLAS_POSITION_FK2 FOREIGN KEY (ACCOUNT_ID)
  REFERENCES ATLAS_ACCOUNT(ACCOUNT_ID);

ALTER TABLE ATLAS_POSITION
  ADD CONSTRAINT ATLAS_POSITION_CHK1 CHECK (QTY >= 0);

ALTER TABLE ATLAS_POSITION
  ADD CONSTRAINT ATLAS_POSITION_UK1
  UNIQUE (ASOF_DT, INSTRUMENT_ID, ACCOUNT_ID);

-- AUDIT: minimal sanity—entity/action non-empty (NOT NULL was set in DDL)

-- Helpful indexes to support FKs (Oracle often creates them automatically for PKs;
-- FKs do NOT auto-index—indexing them reduces locking on parent updates):
CREATE INDEX ATLAS_TRADE_I1   ON ATLAS_TRADE(INSTRUMENT_ID);
CREATE INDEX ATLAS_TRADE_I2   ON ATLAS_TRADE(ACCOUNT_ID);
CREATE INDEX ATLAS_POSITION_I1 ON ATLAS_POSITION(INSTRUMENT_ID);
CREATE INDEX ATLAS_POSITION_I2 ON ATLAS_POSITION(ACCOUNT_ID);
