--------------------------------------------------------------------------------
-- ATLAS Investment Demo - Seed Data
-- Assumes ALTER SESSION NLS_DATE_FORMAT = 'YYYY-MM-DD' (from 000_init_schema.sql)
--------------------------------------------------------------------------------

-- Instruments
INSERT INTO ATLAS_INSTRUMENT (SYMBOL, INSTRUMENT_TYPE, CURRENCY_CODE) VALUES ('AAPL','EQUITY','USD');
INSERT INTO ATLAS_INSTRUMENT (SYMBOL, INSTRUMENT_TYPE, CURRENCY_CODE) VALUES ('MSFT','EQUITY','USD');
INSERT INTO ATLAS_INSTRUMENT (SYMBOL, INSTRUMENT_TYPE, CURRENCY_CODE) VALUES ('BNDKWT','BOND','KWD');
INSERT INTO ATLAS_INSTRUMENT (SYMBOL, INSTRUMENT_TYPE, CURRENCY_CODE) VALUES ('KUWETF','FUND','KWD');
INSERT INTO ATLAS_INSTRUMENT (SYMBOL, INSTRUMENT_TYPE, CURRENCY_CODE) VALUES ('EURUSD','FX','USD');

-- Accounts (two regions for later RLS demo)
INSERT INTO ATLAS_ACCOUNT (ACCOUNT_NAME, REGION_CODE) VALUES ('Pension Fund A','KWT');
INSERT INTO ATLAS_ACCOUNT (ACCOUNT_NAME, REGION_CODE) VALUES ('Sovereign Portfolio 1','KWT');
INSERT INTO ATLAS_ACCOUNT (ACCOUNT_NAME, REGION_CODE) VALUES ('External Fund EMEA','EMEA');
INSERT INTO ATLAS_ACCOUNT (ACCOUNT_NAME, REGION_CODE) VALUES ('Index Strategy USD','EMEA');
INSERT INTO ATLAS_ACCOUNT (ACCOUNT_NAME, REGION_CODE) VALUES ('Trading Desk X','KWT');

-- Helper: get IDs for consistent inserts
-- (In LiveSQL you can SELECT them; below we just inline simple SELECTs)

-- Trades (mix BUY/SELL across symbols, accounts, and dates)
INSERT INTO ATLAS_TRADE (TRADE_DT, INSTRUMENT_ID, ACCOUNT_ID, SIDE, QTY, PRICE, ENTERED_BY, NOTE)
SELECT DATE '2025-01-05', i.instrument_id, a.account_id, 'BUY',  100, 185.20, 'analyst@atlas', 'initial buy'
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='AAPL' AND a.ACCOUNT_NAME='Pension Fund A';

INSERT INTO ATLAS_TRADE (TRADE_DT, INSTRUMENT_ID, ACCOUNT_ID, SIDE, QTY, PRICE, ENTERED_BY, NOTE)
SELECT DATE '2025-01-06', i.instrument_id, a.account_id, 'BUY',   80,  402.10, 'analyst@atlas', 'growth allocation'
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='MSFT' AND a.ACCOUNT_NAME='Pension Fund A';

INSERT INTO ATLAS_TRADE (TRADE_DT, INSTRUMENT_ID, ACCOUNT_ID, SIDE, QTY, PRICE, ENTERED_BY, NOTE)
SELECT DATE '2025-01-06', i.instrument_id, a.account_id, 'SELL',  50,  186.10, 'manager@atlas', 'rebalance'
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='AAPL' AND a.ACCOUNT_NAME='Pension Fund A';

INSERT INTO ATLAS_TRADE (TRADE_DT, INSTRUMENT_ID, ACCOUNT_ID, SIDE, QTY, PRICE, ENTERED_BY, NOTE)
SELECT DATE '2025-01-07', i.instrument_id, a.account_id, 'BUY',  1000,  1.1020, 'desk@atlas', 'fx hedge'
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='EURUSD' AND a.ACCOUNT_NAME='External Fund EMEA';

INSERT INTO ATLAS_TRADE (TRADE_DT, INSTRUMENT_ID, ACCOUNT_ID, SIDE, QTY, PRICE, ENTERED_BY, NOTE)
SELECT DATE '2025-01-08', i.instrument_id, a.account_id, 'BUY',   200,  10.50, 'analyst@atlas', 'bond position'
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='BNDKWT' AND a.ACCOUNT_NAME='Sovereign Portfolio 1';

INSERT INTO ATLAS_TRADE (TRADE_DT, INSTRUMENT_ID, ACCOUNT_ID, SIDE, QTY, PRICE, ENTERED_BY, NOTE)
SELECT DATE '2025-01-09', i.instrument_id, a.account_id, 'SELL',  100,  10.65, 'manager@atlas', 'trim bonds'
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='BNDKWT' AND a.ACCOUNT_NAME='Sovereign Portfolio 1';

-- A few more for variety
INSERT INTO ATLAS_TRADE (TRADE_DT, INSTRUMENT_ID, ACCOUNT_ID, SIDE, QTY, PRICE, ENTERED_BY)
SELECT DATE '2025-01-10', i.instrument_id, a.account_id, 'BUY',  300,  27.30, 'analyst@atlas'
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='KUWETF' AND a.ACCOUNT_NAME='Trading Desk X';

INSERT INTO ATLAS_TRADE (TRADE_DT, INSTRUMENT_ID, ACCOUNT_ID, SIDE, QTY, PRICE, ENTERED_BY)
SELECT DATE '2025-01-10', i.instrument_id, a.account_id, 'SELL',  40,  403.00, 'manager@atlas'
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='MSFT' AND a.ACCOUNT_NAME='Pension Fund A';

-- Position snapshots (one date)
INSERT INTO ATLAS_POSITION (ASOF_DT, INSTRUMENT_ID, ACCOUNT_ID, QTY)
SELECT DATE '2025-01-10', i.instrument_id, a.account_id, 130   -- net after sample trades
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='AAPL'   AND a.ACCOUNT_NAME='Pension Fund A';

INSERT INTO ATLAS_POSITION (ASOF_DT, INSTRUMENT_ID, ACCOUNT_ID, QTY)
SELECT DATE '2025-01-10', i.instrument_id, a.account_id, 40
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='MSFT'   AND a.ACCOUNT_NAME='Pension Fund A';

INSERT INTO ATLAS_POSITION (ASOF_DT, INSTRUMENT_ID, ACCOUNT_ID, QTY)
SELECT DATE '2025-01-10', i.instrument_id, a.account_id, 900
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='EURUSD' AND a.ACCOUNT_NAME='External Fund EMEA';

INSERT INTO ATLAS_POSITION (ASOF_DT, INSTRUMENT_ID, ACCOUNT_ID, QTY)
SELECT DATE '2025-01-10', i.instrument_id, a.account_id, 100
FROM ATLAS_INSTRUMENT i, ATLAS_ACCOUNT a
WHERE i.SYMBOL='BNDKWT' AND a.ACCOUNT_NAME='Sovereign Portfolio 1';

COMMIT;
