-- Quick validation queries (run in LiveSQL)
-- Counts
SELECT 'INSTRUMENT' obj, COUNT(*) FROM ATLAS_INSTRUMENT
UNION ALL SELECT 'ACCOUNT', COUNT(*) FROM ATLAS_ACCOUNT
UNION ALL SELECT 'TRADE', COUNT(*) FROM ATLAS_TRADE
UNION ALL SELECT 'POSITION', COUNT(*) FROM ATLAS_POSITION;

-- Constraint smoke tests (should return zero rows)
SELECT * FROM ATLAS_TRADE WHERE SIDE NOT IN ('BUY','SELL');
SELECT * FROM ATLAS_TRADE WHERE QTY <= 0 OR PRICE <= 0;

-- Join sample
SELECT t.TRADE_DT, i.SYMBOL, a.ACCOUNT_NAME, t.SIDE, t.QTY, t.PRICE
FROM ATLAS_TRADE t
JOIN ATLAS_INSTRUMENT i ON i.INSTRUMENT_ID = t.INSTRUMENT_ID
JOIN ATLAS_ACCOUNT   a ON a.ACCOUNT_ID    = t.ACCOUNT_ID
ORDER BY t.TRADE_DT, i.SYMBOL;
